### ISSUE TITLE
Failed authorization

### ISSUE THREAD

**Issue by alyan2008** [dlopes7/appdynamics-grafana-datasource#3]
Hi

I am trying to start using your datasource but found one problem:

When trying to add new datasource, I specify correct user and password (user has full access) but grafana still asking login/password and after two attempt grafana wrote - "Unauthorized"

AppD version - 4.3.4.2
Controller - On Premise

Screens have been attached.

Please let me know if I do something wrong

![screen_2](https://user-images.githubusercontent.com/7196207/30350794-e67dd448-9820-11e7-9b95-8d11cc87d9d7.png)
![screen_1](https://user-images.githubusercontent.com/7196207/30350795-e67e9676-9820-11e7-889b-915b573f7e38.png)

**Comment by dlopes7** [comment]
Hello Alyan,

Thanks for using the plugin.
You have to use duke@<accountname> as the username.

On an OnPrem controller, it usually is duke@**customer1**

More details here https://docs.appdynamics.com/display/PRO43/Using+the+Controller+APIs at the Authentication session!

Regards

**Comment by alyan2008** [comment]
Thanks, it works!
