### ISSUE TITLE
getMetricNames error

### ISSUE THREAD

**Issue by danga03** [dlopes7/appdynamics-grafana-datasource#5]
I found the following incorrect reference for templating in getNameMetrics. 

AppDynamicsSDK.prototype.getMetricNames = function (app, query) {
        var _this = this;
        var templatedApp = this.templateSrv.replace(app);
        var templatedQuery = this.templateSrv.replace(query);
        var params = { output: 'json' };
        if (query.indexOf('|') > -1) {
            params['metric-path'] = query; <-- this line needs to be changed from 'query' to 'templatedQuery' 
        }

**Comment by dlopes7** [comment]
Thanks for the catch! Templating is very much a work in progress
